// Generated by CoffeeScript 1.6.2
(function() {
  var creatureMaker,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  creatureMaker = (function() {
    function creatureMaker(view) {
      this.view = view;
      this.make = __bind(this.make, this);
    }

    creatureMaker.prototype.make = function(location) {
      this.location = location;
    };

    return creatureMaker;

  })();

}).call(this);
