// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var initalize;

    initalize = function() {
      return window.app = new SandboxOcean();
    };
    return initalize();
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
