// Generated by CoffeeScript 1.6.2
(function() {
  var Point;

  Point = (function() {
    function Point(x, y) {
      this.x = x;
      this.y = y;
    }

    return Point;

  })();

  window.Point = Point;

}).call(this);
