// Generated by CoffeeScript 1.6.2
(function() {
  var DefaultUnitConfig, species;

  species = ["sea-creature", "beach-creature", "land-creature"];

  DefaultUnitConfig = (function() {
    function DefaultUnitConfig() {
      this.config = {
        name: "nimo",
        species: "sea-creature",
        view: {
          id: 0,
          animateType: "sprite"
        },
        scale: {
          xy: Math.random() * .3 + .7,
          x: 1,
          y: 1
        },
        position: {
          x: 0,
          y: 0
        },
        rotation: 0,
        moveType: "movable",
        moveSpeed: .1,
        rotationType: true,
        rotateSpeed: .1,
        life: {
          total: 1,
          birthTime: 0
        },
        habitat: {
          restricted: true,
          from: "coast",
          to: "deepSea"
        }
      };
      return this.config;
    }

    return DefaultUnitConfig;

  })();

  window.DefaultUnitConfig = DefaultUnitConfig;

}).call(this);

/*
//@ sourceMappingURL=UnitConfig.map
*/
