// Generated by CoffeeScript 1.6.2
(function() {
  var Fish,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Fish = (function() {
    function Fish(view) {
      this.view = view;
      this.death = __bind(this.death, this);
      this.birth = __bind(this.birth, this);
      this.movable = new Movable(this.view);
    }

    Fish.prototype.birth = function() {
      this.movable.birth();
      return stage.addChild(this.view);
    };

    Fish.prototype.death = function() {
      this.movable.death();
      return stage.removeChild(this.view);
    };

    return Fish;

  })();

  window.Fish = Fish;

}).call(this);
