// Generated by CoffeeScript 1.6.2
(function() {
  var DiffChecker;

  DiffChecker = (function() {
    function DiffChecker() {}

    return DiffChecker;

  })();

  window.DiffChecker = DiffChecker;

}).call(this);

/*
//@ sourceMappingURL=diffChecker.map
*/
