// Generated by CoffeeScript 1.6.2
(function() {
  var LocationChecker,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  LocationChecker = (function() {
    function LocationChecker(parent) {
      this.parent = parent;
      this.locationCheck = __bind(this.locationCheck, this);
      this.loop = __bind(this.loop, this);
      this.view = this.parent.view;
      this.config = this.parent.config;
      this.loop();
      this.depth = window.depth;
    }

    LocationChecker.prototype.loop = function() {
      requestAnimFrame(this.loop);
      return this.locationCheck();
    };

    LocationChecker.prototype.locationCheck = function() {
      var result, x, y;

      if (this.parent.life === 0) {
        return;
      }
      x = parseInt(this.view.x);
      y = parseInt(this.view.y);
      if (x && y) {
        result = window.depth.getDepthLevelToDOA(x, y, this.config);
        if (result === "over" || result === "under") {
          return $(this).trigger(result);
        }
      }
    };

    return LocationChecker;

  })();

  window.LocationChecker = LocationChecker;

}).call(this);

/*
//@ sourceMappingURL=LocationChecker.map
*/
